xwiki/xwiki-rendering

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/EmptyLinesBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/FormatBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/HeaderBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/IdBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/ImageBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/LinkBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/ListBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/MacroBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/MacroMarkerBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/RawTextBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/SpecialSymbolBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/VerbatimBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/WordBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/XDOMXMLContentHandlerStreamParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/XDOMXMLParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/renderer/XDOMXMLContentHandlerStreamRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/renderer/XDOMXMLRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxmlcurrent/src/main/java/org/xwiki/rendering/xdomxmlcurrent/internal/parser/XDOMXMLContentHandlerStreamParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxmlcurrent/src/main/java/org/xwiki/rendering/xdomxmlcurrent/internal/parser/XDOMXMLParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxmlcurrent/src/main/java/org/xwiki/rendering/xdomxmlcurrent/internal/renderer/XDOMXMLRenderer.java
There was a few deprecated used of `@Component("something")` instead of 
```
@Component
@Named("something")
```
=> Component deprecated

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/listener/descriptor/DefaultListenerDescriptorManager.java
toUpperCase() and toLowerCase() can cause problems with other languages such as Turkish. This is because toLowerCase() actually calls toLowerCase(Locale.default) and the default locale varies based on location.
=> [codestyle] changed locale to english

xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/macro/DefaultMacroManager.java
Changed comparison to use the `.equals()` method. This resolves the issue [here](http://sonar.xwiki.org/coding_rules#rule_key=squid%3AS1698)
=> [codestyle] Change comparison to use equals method

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiImageTagHandler.java
getValue() might be null even if classParam isn't
http://sonar.xwiki.org/issues/search#issues=c8e016a7-c1f8-4f4a-9e94-8f1bc018f96d
http://sonar.xwiki.org/issues/search#issues=0c51b787-ec53-4935-b64f-ec4fda5c5a43
http://sonar.xwiki.org/issues/search#issues=f0613c7f-5b8c-4868-9ea6-4093a46224a0
=> [codestyle] removed useless parentheses and reordered .equals

xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/WikiModelParserUtils.java
1.  http://sonar.xwiki.org/issues/search#issues=3c1b185e-bf69-40e1-b961-51d0fb5ac04e
2.  http://sonar.xwiki.org/issues/search#issues=436a2f3b-043e-4798-85a7-54d6456664ce
=> [codestyle] Avoid using redundant field initializer for 'foundWord'

xwiki-rendering-syntaxes/xwiki-rendering-syntax-doxia/src/main/java/org/xwiki/rendering/internal/parser/doxia/XWikiGeneratorSink.java
I changed the variable from a StringBuffer to a StringBuilder. No other changes were needed as the methods used in the program work for both string classes.
=> [codestyle] Replace the synchronized class "StringBuffer" by an unsynchronized one such as "StringBuilder". 

xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/DefaultFigureTypeRecognizer.java
Fixed all the issues in [this file](http://sonar.xwiki.org/dashboard/index?id=org.xwiki.rendering%3Axwiki-rendering-macro-figure%3Asrc%2Fmain%2Fjava%2Forg%2Fxwiki%2Frendering%2Finternal%2Fmacro%2Ffigure%2FDefaultFigureTypeRecognizer.java)
Solves Issues:
[Remove those useless parentheses](http://sonar.xwiki.org/issues/search#issues=fc0542e0-7aae-42b2-aa5b-883f244ef4c6) 
[Move the "figureCaption" string literal on the left side of this string comparison](http://sonar.xwiki.org/issues/search#issues=db82d5e0-27c6-4985-8dc4-bb7819307182)
[ Method org.xwiki.rendering.internal.macro.figure.DefaultFigureTypeRecognizer.getBlocksIgnoringMacro MarkerBlocks(List) makes literal string comparisons passing the literal as an argument
](http://sonar.xwiki.org/issues/search#issues=2369df49-720a-4750-9294-4f …
=> Fixed Sonar Issues in DefaultFigureTypeRecognizer

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/ImageBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/LinkBlockParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xdomxml10/src/main/java/org/xwiki/rendering/xdomxml10/internal/parser/MetaDataBlockParser.java, xwiki-rendering-test/src/main/java/org/xwiki/rendering/test/integration/TestDataGenerator.java, xwiki-rendering-test/src/main/java/org/xwiki/rendering/test/integration/TestDataParser.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/handler/AbstractFormatTagHandler.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/handler/ReferenceTagHandler.java
Fixed all issues in rendering for this rule: Strings literals should be placed on the left side when checking for equality
Solves: 
http://sonar.xwiki.org/issues/search#issues=94d88eaa-64b4-4e8d-99dc-712e4d462df6
http://sonar.xwiki.org/issues/search#issues=cad4d31e-b582-4744-bcab-0087f28408b4
http://sonar.xwiki.org/issues/search#issues=64748edd-ebd1-4ebe-bcdf-73af94121541
http://sonar.xwiki.org/issues/search#issues=4fc8f468-9189-4fcb-aee9-3b8391a0bdd7
http://sonar.xwiki.org/issues/search#issues=da91b94a-de95-4859-a276-9c5d7b437f8f
http://sonar.xwiki.org/issues/search#issues=4f0ab54a-aa97-4c9e-aff1-c5c319c34746
http://sonar.xwiki.org/issues/search#issues=2981b895-dc0e-424e-bfff-00a964e99c2d
http://sonar.xwiki.org/issues/search#issues=805dacf1-24e1-4d89-9313-23e087e0bdb2 …
=> Fixed all Strings literals on left issues

xwiki-rendering-macros/xwiki-rendering-macro-content/pom.xml, xwiki-rendering-macros/xwiki-rendering-macro-content/src/main/java/org/xwiki/rendering/internal/macro/content/ContentMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-content/src/test/resources/macrocontent3.test
https://jira.xwiki.org/browse/XRENDERING-523
* Set the syntax directly in the parent node as parameter, if there's
only one
* Add a new metadatablock with the syntax if there's multiples blocks
* Add a new test to check this latter case
=> XRENDERING-523: Set the syntax in Macro Content

xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedxhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/AnnotatedXHTMLChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedxhtml/src/test/resources/annotatedxhtml10/simple/metadata/metadata1.out.txt, xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/DefaultXWikiGeneratorListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XHTMLXWikiGeneratorListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/simple/metadata/metadata1.in.txt, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/metadata/metadata1.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/metadata/metadata2.test, xwiki-rendering-test/src/main/resources/cts/simple/metadata/metadata1.inout.xml
* Create a new dedicated block for metadata in
AnnotatedXHTMLChainingRenderer
=> XRENDERING-527: HTML renderer should handle metadata to create dedicated attribute

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/InlineFilterListener.java
* Also skip groups in InlineFilterListener
=> XRENDERING-518: The macro content descriptor should specify if it can be edited inline

xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/FigureCaptionMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/FigureMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure1.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure2.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure3.test
* Allow figure and FigureCaption to be editable inline. Change tests
accordingly.
=> XRENDERING-538: Figure and FigureCaption macros should be editable inline

xwiki-rendering-integration-tests/pom.xml, xwiki-rendering-integration-tests/src/test/resources/simple/macros/macro25.test, xwiki-rendering-integration-tests/src/test/resources/simple/macros/macro26.test
* Ensure the behaviour of box macro with empty or null content for
inline editing
=> XRENDERING-541: You can no longer insert content to inlinemacro without selecting beforehand

xwiki-rendering-integration-tests/src/test/resources/simple/macros/macro27.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiCommentHandler.java
* Protect XWikiCommentHandler#handleMacroCommentStop in case no macro
info is available in the context
=> XWIKI-15914: Cannot add Attachment Selector Macro into a page

xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/descriptor/DefaultParameterDescriptor.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/descriptor/ParameterDescriptor.java
https://jira.xwiki.org/browse/XCOMMONS-1558
* Add the display type in the parameter descriptor.
See https://github.com/xwiki/xwiki-commons/pull/64.
=> XRENDERING-553: Expose the display type property in the parameter descriptors

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/MetaData.java, xwiki-rendering-integration-tests/src/test/resources/simple/macros/macro28.test, xwiki-rendering-integration-tests/src/test/resources/simple/macros/macro29.test, xwiki-rendering-macros/xwiki-rendering-macro-box/pom.xml, xwiki-rendering-macros/xwiki-rendering-macro-box/src/main/java/org/xwiki/rendering/macro/box/AbstractBoxMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/main/java/org/xwiki/rendering/macro/box/BoxMacroParameters.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/test/resources/macrobox5.test, xwiki-rendering-macros/xwiki-rendering-macro-box/src/test/resources/macrobox8.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiMacroHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiWikiModelHandler.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/AbstractMacro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/descriptor/DefaultParameterDescriptor.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/TestInlineEditingMacroParameter.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/TestMacroParameter.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/macro/AbstractMacroTest.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/impl/MacroInfo.java
https://jira.xwiki.org/browse/XRENDERING-556
* Define a new metadata attribute for identifying parameter
* Define an utility method in AbstractMacro to create a non generated
metadata for a specific parameter
* Specify that the title block is non generated in BoxMacro
* Add new tests for both rendering and parsing of BoxMacro
* Handle the new metadata attribute when setting the content in
XWikiMacroHandler
* Upgrade Macro Box tests
=> XRENDERING-556: Allow to parse inline editable macro parameters in html result

pom.xml, xwiki-rendering-integration-tests/src/test/resources/simple/macros/macro30.test, xwiki-rendering-integration-tests/src/test/resources/simple/macros/macro31.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiCommentHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiMacroHandler.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/impl/IgnoreElementRule.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/impl/MacroInfo.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/impl/TagStack.java
https://jira.xwiki.org/browse/XRENDERING-562
The proposed solution is twofolds:
1. I needed to avoid switching the IgnoreElementRule each time a non-generated content div is found, but to use the state of the rule itself. I had to change its API for that but I guess it's ok since it was unstable. 
2. I also needed to ensure that only one scanner is created for the content of the macro, to avoid to reset its content to an empty value when going into the second closing non-generated div.
=> XRENDERING-562: Support of redundant non-generated content div

xwiki-rendering-syntaxes/xwiki-rendering-syntax-docbook/src/test/resources/docbook44/config.properties
Removing the failingTests filter since it does not fails anymore.
=> XRENDERING-141: Docbook parser fails to support Italic syntax nested inside Bold syntax

xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/XhtmlParser.java, xwiki-rendering-xml/src/main/java/org/xwiki/rendering/xml/internal/parser/AbstractStreamParser.java
Sets the `FEATURE_SECURE_PROCESSING` feature in the `SAXParserFactory`. One of the classes could be modified to retrieve the `XMLReader` from `ComponentManager` instead, but I'm not sure of the possible side-effects of that.
It also sets an `EntityResolver` so DTDs can be found (the `XMLReader` no longer retrieves everything). Breakages arising from this change could be possible, if a processed document is using an unsafe `DOCTYPE` declaration.
=> XRENDERING-592: Unsafe production of XMLReader objects

xwiki-rendering-api/src/main/java/org/xwiki/rendering/syntax/SyntaxType.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/XHTMLChainingRenderer.java
These changes are related to a PR opened on the xwiki-platform https://github.com/xwiki/xwiki-platform/pull/1700#discussion_r726829978
=> [MISC] Move XHTMLChainingRenderer#HTML_TYPES to SyntaxType to avoid forgetting syntaxes from the HTML group

xwiki-rendering-api/pom.xml, xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/BlockStateChainingListener.java, xwiki-rendering-api/src/test/java/org/xwiki/rendering/listener/chaining/BlockStateChainingListenerTest.java
* Add unit tests to test previous event information
* Handle group and metadata events
* Only set the previous event information after handling an event
Jira issue: https://jira.xwiki.org/browse/XRENDERING-636
Note: I have created this unit test primarily for https://jira.xwiki.org/browse/XRENDERING-631 where, in the implementation, I add a new method to get the parent event of an event and slightly extend this test to test for the correct parent event, too, see https://github.com/michitux/xwiki-rendering/commit/4d936b9ff7f0c954b0d8c338dd6ab9815bae6421 (I will open a PR for that once this one has been merged). Further, this can be seen as a prototype for https://jira.xwiki.org/browse/XRENDERING-633
=> XRENDERING-636: Previous event information in BlockStateChainingListener is inconsistent

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/BlockStateChainingListener.java, xwiki-rendering-api/src/test/java/org/xwiki/rendering/listener/chaining/BlockStateChainingListenerTest.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedhtml5/src/main/java/org/xwiki/rendering/internal/renderer/html5/AnnotatedHTML5ChainingRenderer.java
* Change the annotated HTML5 renderer to only render figure captions when inside a figure.
* Extend BlockStateChainingListener with an event stack to allow getting the parent event.
* Extend BlockStateChainingListenerTest to test for parent events.
As proposed in #191, the renderer could also render `<div class="figcaption">` or a similar tag instead of the `<figcaption>`-tag as it would be nice to have at least some HTML tag in the output to identify the caption (it's just that `<figcaption>` is only allowed as direct child of `<figure>`), see also https://jira.xwiki.org/browse/XRENDERING-625 - I haven't included it here as I haven't received any feedback on the proposed `<div>`-tag in #191 yet.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-631
=> XRENDERING-631: The annotated HTML5 renderer should not render figcaption inside macros

xwiki-rendering-macros/xwiki-rendering-macro-html/src/test/resources/macrohtml19.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedhtml5/src/main/java/org/xwiki/rendering/internal/renderer/html5/AnnotatedHTML5ChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedhtml5/src/test/java/org/xwiki/rendering/internal/html5/AnnotatedHTML5SpecificTest.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedhtml5/src/test/resources/annotatedhtml50/simple/metadata/metadata1.out.txt, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedhtml5/src/test/resources/annotatedhtml50/specific/metadata/metadata1.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedxhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/AnnotatedXHTMLChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedxhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/XHTMLMetaDataRenderer.java
* Render macro markers also for nested macros
* Extract a class XHTMLMetaDataRenderer to avoid code duplication
* Render metadata blocks
* Add metadata test to the annotated HTML5 renderer
Jira issue: https://jira.xwiki.org/browse/XRENDERING-630
=> XRENDERING-630: The annotated HTML5 renderer doesn't render all metadata for macros

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/link/link6.test
* Add mising comment to test
Original Jira issue: https://jira.xwiki.org/browse/XRENDERING-612 - fixing https://github.com/xwiki/xwiki-rendering/pull/196#discussion_r783900776
=> XRENDERING-612: Mailto links are incorrectly parsed (fix)

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/syntax/DefaultSyntaxRegistry.java
Varargs support was added to `NoWhitespaceAfterCheck`, [CI](https://app.circleci.com/pipelines/github/checkstyle/checkstyle/11189/workflows/a123a7dc-6104-4ea2-817b-c0c0d2a6b2a3/jobs/111316?invite=true#step-102-2909) was failing on XWiki.
CS PR: https://github.com/checkstyle/checkstyle/pull/11198
=> [Misc] Update DefaultSyntaxRegistry.java

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/AbstractChainingListener.java, xwiki-rendering-api/src/test/java/org/xwiki/rendering/listener/chaining/AbstractChainingListenerTest.java, xwiki-rendering-api/src/test/java/org/xwiki/rendering/listener/chaining/BlockStateChainingListenerTest.java, xwiki-rendering-api/src/test/java/org/xwiki/rendering/test/ListenerMethodProvider.java
* Extract a ListenerMethodProvider from BlockStateChainingListenerTest.
* Add separate compatibility mode for endListItem without parameters.
* Extend AbstractChainingListenerTest to test that all methods correctly forward in the chain.
* Some coding style/SonarLint fixes.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-644
I assume this should be cherry-picked to 13.10, that's why I added `@since 13.10.3`-tags in addition to `@since 14.1RC1`.
=> XRENDERING-644: AbstractChainingListener has no compatibility mode for endListItem without parameters

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/BlockStateChainingListener.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/FigureCaptionMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/FigureMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure1.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure2.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure3.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure4.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure5.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-html5/src/test/resources/html50/specific/figure/figure1.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/XHTMLChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/java/org/xwiki/rendering/internal/renderer/xhtml/XHTMLChainingRendererTest.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/AbstractStackingInlineContentChainingListener.java
* Put the `FigureBlock` and `FigureCaptionBlock` outside the `MetaDataBlock` that wraps the editable content.
* Mark `FigureCaptionBlock` as container for block-level elements. This is consistent with HTML5 and required to keep the caption editable in CKEditor.
* Add a new test case that contains an image.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-629
=> XRENDERING-629: The figure and figure caption should not be part of the editable content

xwiki-rendering-api/pom.xml, xwiki-rendering-api/src/test/java/org/xwiki/rendering/listener/CompositeListenerTest.java, xwiki-rendering-api/src/test/java/org/xwiki/rendering/listener/chaining/LookaheadChainingListenerTest.java
* Check in LookaheadChainingListenerTest that all methods are implemented, forward the correct event and give the correct lookahead.
* Added test case for CompositeListener.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-633
=> XRENDERING-633: Add test cases to check generic listeners implement all methods

xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/HeaderBlock.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/ImageBlock.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/parser/Parser.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/parser/StreamParser.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/util/IdGenerator.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/test/resources/macrobox10.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-doxia/src/main/java/org/xwiki/rendering/internal/parser/doxia/AbstractDoxiaParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-html/src/main/java/org/xwiki/rendering/internal/parser/html/HTMLParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-html5/src/main/java/org/xwiki/rendering/internal/parser/html5/HTML5Parser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/AbstractWikiModelParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/DefaultXWikiGeneratorListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/WikiModelParserUtils.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/XHTMLParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/test/resources/xwiki20/specific/image/image4.test, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/macro/DefaultMacroContentParser.java
* Ensure that ids are unique also when nested in links or macros.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-6
=> XRENDERING-6: Id are not unique when included document or macro content has the same headers as the top document

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XHTMLXWikiGeneratorListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/group/group1.test
All tests are passing and I've manually tested editing
```
{{warning}}
Warning!
{{warning}}{{success}}Nested macros are editable!{{/success}}{{/warning}}
{{success}}Success message is inline-editable!{{/success}}
{{/warning}}
(% data-xwiki-attribute="value" %)
(((
Some section content!
)))
```
in the WYSIWYG editor and it worked.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-668
=> XRENDERING-668: Attributes starting with data-xwiki- aren't preserved during XHTML parsing

xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/macro/DefaultMacroCategoryManager.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/MacroCategoryManager.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/macro/DefaultMacroCategoryManagerTest.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/macro/DefaultMacroIdFactoryTest.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/macro/DefaultMacroManagerTest.java
Introduce `MacroCategoryManager#getMacroCategories(org.xwiki.rendering.macro.MacroId)` and its implementation `DefaultMacroCategoryManager#getMacroCategories(org.xwiki.rendering.macro.MacroId)`
Jira: https://jira.xwiki.org/browse/XRENDERING-672
=> XRENDERING-672: Provide a way to list the categories of a macro

xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/FigureMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/FigureTypeRecognizerMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/resources/META-INF/components.txt, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure1.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure3.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure4.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure5.test, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure6.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-html5/src/test/resources/html50/specific/figure/figure1.test, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/AbstractMacro.java
- Introduce the Hidden macro type
- Introduce the FigureTypeRecognizerMacro
- Use FigureTypeRecognizerMacro in FigureMacro
- Test updated in xwiki-macro-rendering-figure and xwiki-rendering-syntax-html5
Jira: https://jira.xwiki.org/browse/XRENDERING-665
=> XRENDERING-655: Add the ability to style image captions

xwiki-rendering-macros/xwiki-rendering-macro-html/src/main/java/org/xwiki/rendering/internal/macro/html/HTMLMacro.java, xwiki-rendering-test/src/main/java/org/xwiki/rendering/test/integration/AbstractRenderingTest.java
* Use the appropriate context component manager in HTMLMacro
* Fix the rendering test to register a context component manager
instance
=> XRENDERING-678: Cannot use HtmlMacro with a syntax installed on a subwiki

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/pom.xml, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/XHTMLParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XHTMLXWikiGeneratorListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiCommentHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiReferenceTagHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiWikiReference.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml5/src/main/java/org/xwiki/rendering/internal/parser/xhtml5/XHTML5Parser.java
* Pass the label via an XDOM instance instead of rendering/parsing to xdom+xml syntax.
* Move the reference type detection into the XWikiReferenceTagHandler to simplify XHTMLXWikiGeneratorListener.
I'm not super happy with the new workaround but I think it's better than the old one, avoids the dependency on another syntax and shouldn't cause any breakages as we're (mostly) still doing the same. The better design would be to introduce begin/end methods for references but then we would need (probably) major changes in WikiModel to properly support everything that currently works like having independent styling in link labels.
=> XRENDERING-660: Get rid of the dependency on the xdom+xml syntax

xwiki-rendering-macros/xwiki-rendering-macro-content/pom.xml, xwiki-rendering-macros/xwiki-rendering-macro-content/src/test/resources/macrocontent4.test, xwiki-rendering-macros/xwiki-rendering-macro-html/src/main/java/org/xwiki/rendering/internal/macro/html/renderers/annotatedhtml5/HTMLMacroAnnotatedHTML5Renderer.java, xwiki-rendering-macros/xwiki-rendering-macro-html/src/main/java/org/xwiki/rendering/internal/macro/html/renderers/annotatedxhtml/HTMLMacroAnnotatedXHTMLRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedhtml5/src/main/java/org/xwiki/rendering/internal/renderer/html5/AnnotatedHTML5ChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedhtml5/src/main/java/org/xwiki/rendering/internal/renderer/html5/AnnotatedHTML5Renderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedxhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/AnnotatedXHTMLChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedxhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/AnnotatedXHTMLRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedxhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/XHTMLMetaDataRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-annotatedxhtml/src/main/resources/META-INF/components.txt, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiMacroHandler.java
* Use ConverterManager to serialize metadata to strings.
* Fix wrong inject in non-component.
* Add integration test for verifying that parsing from HTML actually works.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-702
=> XRENDERING-702: The content macro breaks WYSIWYG editing

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/BlockStateChainingListener.java, xwiki-rendering-api/src/test/java/org/xwiki/rendering/internal/syntax/SyntaxRegistryListenerTest.java, xwiki-rendering-api/src/test/java/org/xwiki/rendering/listener/chaining/AbstractChainingListenerTest.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/WikiModelParserUtils.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/impl/WikiScannerContext.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xwiki/xwiki20/XWikiSerializer2.java
minor: make private class final with default constructor
This is part of https://github.com/checkstyle/checkstyle/pull/12737
According to the https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.8.9 The default constructor has the same access modifier as the class.
and according to the check https://checkstyle.org/config_design.html#FinalClass a class that has only private constructors and has no descendant classes is declared as final.
=> minor: make private class final with default constructor

xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/TocBlockFilter.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc11.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc14.test
Jira: https://jira.xwiki.org/browse/XRENDERING-707
=> XRENDERING-707: The toc macro use the name of the page for empty headers entries

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/XHTMLParser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiHeadTagHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiIgnoredTagHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/head/head1.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/script/script1.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml5/pom.xml, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml5/src/main/java/org/xwiki/rendering/internal/parser/xhtml5/XHTML5Parser.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml5/src/test/java/org/xwiki/rendering/internal/xhtml5/XHTML5SpecificTest.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml5/src/test/resources/xhtml5/specific/head/head1.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml5/src/test/resources/xhtml5/specific/script/script1.test
Jira: https://jira.xwiki.org/browse/XRENDERING-721
**TODO**
=> XRENDERING-721: Content of script tags should be ignored to avoid additional content being saved

xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/AbstractBlock.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/Block.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/XDOM.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/match/FunctionBlockMatcher.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/match/MetadataBlockMatcher.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/main/java/org/xwiki/rendering/internal/macro/box/DefaultBoxMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/main/java/org/xwiki/rendering/macro/box/AbstractBoxMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/test/java/org/xwiki/rendering/internal/macro/box/DefaultBoxMacroTest.java, xwiki-rendering-macros/xwiki-rendering-macro-content/src/main/java/org/xwiki/rendering/internal/macro/content/ContentMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-footnotes/src/main/java/org/xwiki/rendering/internal/macro/footnote/FootnoteMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-html/src/main/java/org/xwiki/rendering/internal/macro/html/HTMLMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-message/src/main/java/org/xwiki/rendering/internal/macro/message/AbstractMessageMacro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/macro/DefaultMacroContentParser.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/MacroContentParser.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/macro/DefaultMacroContentParserTest.java
The idea is to parse and prepare the content of macros for which content is parsed as wiki content:
* box
* info
* warning
* error
* success
* content
* footnote
* html
Most of the work is actually done by `MacroContentParser` which got a new API to help with the preparation of macro containing wiki content.
I also added a new generic helper in Block to simplify any code that needs to search for some special value among the tree of blocks.
=> XRENDERING-723: Allow preparing macros

.mvn/gradle-enterprise.xml, README.md
- Updated Revved up by Gradle Enterprise badge to say Revved up by Develocity (after GE -> Develocity rename)
- Updated build cache config to only push when authenticated
=> Update gradle enterprise

xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/handler/AbstractFormatTagHandler.java
https://jira.xwiki.org/browse/XRENDERING-739
* Migrate to CSS3 parsing
```
mvn clean install -pl :xwiki-rendering-wikimodel -Pquality
```
* Prefers squash: Yes
=> XRENDERING-739: Migrate to CSS3 parsing

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/AbstractChainingListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiMacroHandler.java
This change defensively switches the order of literals in comparison expressions to ensure that no null pointer exceptions are unexpectedly thrown. Runtime exceptions especially can cause exceptional and unexpected code paths to be taken, and this can result in unexpected behavior. 
Both simple vulnerabilities (like information disclosure) and complex vulnerabilities (like business logic flaws) can take advantage of these unexpected code paths.
Our changes look something like this:
```diff
String fieldName = header.getFieldName();
String fieldValue = header.getFieldValue();
- if(fieldName.equals("requestId")) {
+ if("requestId".equals(fieldName)) {
logRequest(fieldValue);
}
```
<details>
<summary>More reading</summary>
* [https://cwe.mitre.org/data/definitions/476.html](https://cwe.mitre.o …
=> Switch order of literals to prevent NullPointerException 

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/list/list.test, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/handler/ListTagHandler.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/impl/TagContext.java
https://jira.xwiki.org/browse/XRENDERING-744
* Treat lists that are in a list item but where the list item has a nested document as block handlers.
* Bulletproof TagContext.getParent against being called on the root tag context.
Lists that are wrapped in other list items [are not "block handlers"](https://github.com/xwiki/xwiki-rendering/blob/a610c0ce518745875746fc5ab90b706e2649f3c4/xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xhtml/handler/ListTagHandler.java#L39-L42) as they don't require, e.g., a nested document tag. However, as, when the inner list starts, we are directly inside the created group syntax, we are not in a block context when the paragraph is opened. Therefore, the paragraph tag handler doesn't trigger the opening of a nested document. In the …
=> XRENDERING-744: Nested lists with paragraphs are incorrectly rendered and cause NPEs

xwiki-rendering-legacy/xwiki-rendering-legacy-transformations/xwiki-rendering-legacy-transformation-macro/src/main/aspect/org/xwiki/rendering/macro/descriptor/AbstractMacroDescriptorAspect.aj, xwiki-rendering-legacy/xwiki-rendering-legacy-transformations/xwiki-rendering-legacy-transformation-macro/src/main/aspect/org/xwiki/rendering/macro/descriptor/MacroDescriptorAspect.java, xwiki-rendering-legacy/xwiki-rendering-legacy-transformations/xwiki-rendering-legacy-transformation-macro/src/test/java/org/xwiki/rendering/macro/descriptor/DeprecatedMacroDescriptorTest.java
https://jira.xwiki.org/browse/XRENDERING-749
Fix a retro compatibility breakage introduced by XRENDERING-664.
Unit test added in DeprecatedMacroDescriptorTest.
* Prefers squash: Yes 
* Backport on branches: all supported branches
=> XRENDERING-749: Deprecated MacroDescriptor's getDefaultCategory() is ignored

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/ListenerChain.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/test/resources/xwiki20/specific/emptylines/emptylines1.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/test/resources/xwiki20/specific/emptylines/emptylines2.test
* https://jira.xwiki.org/browse/XRENDERING-684
* https://jira.xwiki.org/browse/XRENDERING-667
* https://jira.xwiki.org/browse/XRENDERING-98
Align the renderer with the parser regarding empty line handling:
* At the start of the document, we need two extra newlines.
* At the start of a group, we need one extra newline, unless the group is otherwise empty, then one newline less should be printed.
* After tables, lists and definition lists, we need one extra newline.
This also fixes XRENDERING-667: New lines added when parsing and re-rendering groups in xwiki/2.1
Further, it partially implements XRENDERING-98 for the beginning of the content: Make empty lines at beginning and end of content significant for XWiki Syntax 2.2.
* This doesn't touch the parser as this would break …
=> XRENDERING-684: Empty lines get removed below tables and lists after saving in wysiwyg editor

xwiki-rendering-macros/xwiki-rendering-macro-message/src/main/java/org/xwiki/rendering/internal/macro/message/AbstractMessageMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-message/src/test/java/org/xwiki/rendering/macro/message/MessageMacroTest.java, xwiki-rendering-macros/xwiki-rendering-macro-message/src/test/resources/macromessage1.test, xwiki-rendering-macros/xwiki-rendering-macro-message/src/test/resources/macromessage2.test, xwiki-rendering-macros/xwiki-rendering-macro-message/src/test/resources/macromessage3.test, xwiki-rendering-macros/xwiki-rendering-macro-message/src/test/resources/macromessage4.test
https://jira.xwiki.org/browse/XWIKI-22761
* Updated the returned DOM of the generic message so that the content is always wrapped appart from the icon. It allows for styles used on this macro to be more reliable.
* Updated tests
* the DOM was quite inconsistent because we had the content at the same level as other elements of the message box. Now we made sure the content is always wrapped in a group (when the macro standalone). This way it makes styling the box easier with CSS because you don't have to account for content style interfering with the box style and the box style interfering with content style (at least not more than by CSS inheritance).
Before the PR:
After the PR:
Note that at the end of the screenshot, there's a weird display when we try to use multiline content in an …
=> XRENDERING-768: Multiple paragraphs in the info macro do not result in multiple lines

xwiki-rendering-macros/xwiki-rendering-macro-box/src/main/java/org/xwiki/rendering/internal/macro/box/DefaultBoxMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-comment/src/main/java/org/xwiki/rendering/internal/macro/comment/CommentMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-content/src/main/java/org/xwiki/rendering/internal/macro/content/ContentMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-html/src/main/java/org/xwiki/rendering/internal/macro/html/HTMLMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-id/src/main/java/org/xwiki/rendering/internal/macro/id/IdMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-message/src/main/java/org/xwiki/rendering/internal/macro/message/AbstractMessageMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-raw/src/main/java/org/xwiki/rendering/internal/macro/raw/RawMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/AbstractTocMacro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/pom.xml, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/transformation/macro/IsolatedExecutionConfiguration.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/transformation/macro/MacroTransformation.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/Macro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/resources/META-INF/components.txt, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/macro/DefaultMacroManagerTest.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/IsolatedExecutionConfigurationTest.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/MacroTransformationTest.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/TestNestedMacro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/TestPriorityMacro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/TestRecursiveMacro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/TestReplacementMacro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/TestTwoNestedMacros.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/resources/META-INF/components.txt
https://jira.xwiki.org/browse/XRENDERING-778
* Introduce the concept of isolated macros.
* In the macro transformation, use a priority queue to efficiently process macros in order.
* Don't re-scan the XDOM after executing isolated macros.
This introduces a slight overhead if no macros are isolated. For 5k macros without skin, the overhead seems around 12.16%, so it adds about 14% of execution time in this case. The overhead only depends on the number of macros being in the XDOM not yet executed at the same time, so I think having 5k macros at the top level without any other content is kind of the worst case in terms of overhead.
No UI changes.
```
LANG=C.UTF-8 mvn clean install -Pdocker,legacy,integration-tests,snapshotModules,quality,distribution,flavor-integration-tests,standalone
```
* …
=> XRENDERING-778: Rendering a page with thousands of macros is slow

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxEscapeHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxEscapeWikiPrinter.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/test/resources/xwiki20/specific/table/table3.test
https://jira.xwiki.org/browse/XRENDERING-786
* Escape table syntax when the last printed characters are a parameter syntax.
* Add a test.
* This escapes too much. It would probably be possible to accumulate more data, like to store the text printed since the last newline. However, I'm not sure if it's worth the effort compared to the rare case of a removed escaping character.
No UI changes.
In `xwiki-rendering`:
```
LANG=C.UTF-8 mvn clean install -Pdocker,legacy,integration-tests,standalone
```
* Prefers squash: Yes 
* Backport on branches:
* stable-16.10.x
=> Under some conditions, table characters ("|" and "!!") are not escaped at the beginning of a line in cells

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/pom.xml, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiSpanTagHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/link/link9.test
https://jira.xwiki.org/browse/XRENDERING-572
* Add wikiinternallink to the classes to remove.
* Improve the class removal to work when the class to remove appears several times or in combination with other classes to ensure a proper cleanup the next time the WYSIWYG editor is used.
* Add a test to verify that the class is removed as intended.
* Improve the code style and remove the Checkstyle exclusion.
* The diff might not make this fully clear, but basically we have a set of classes that are produced by the link renderer, all of them being properly removed but `wikiinternallink` which was somehow missing from the list. So the main fix is also removing `wikiinternallink`, but then I added all the extra code to ensure that we're also handling the mess that was created by this bug.
No UI …
=> XRENDERING-572: "wikiinternallink" is duplicated at every edit in CKeditor

xwiki-rendering-integration-tests/src/test/resources/simple/misc/misc7.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java
https://jira.xwiki.org/browse/XRENDERING-798
* Check for empty format to decide what syntax to use for new lines.
* Extend integration test to cover this case.
* This seems to be the first time that a look ahead of 2 is used - but from what I can see, we have the look ahead listener configured with depth 2, so this should be okay.
No UI changes.
Built the full `xwiki-rendering` with quality profile:
```
mvn clean install -Pquality,standalone,legacy
```
* Prefers squash: Yes 
* Backport on branches:
* stable-17.4.x
* stable-16.10.x
=> XRENDERING-798: Line breaks followed by empty format at the end of block elements should be escaped
