xwiki/xwiki-rendering

xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/ListBlock.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/TocMacro.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xwiki/xwiki-rendering/12)
=> Fix the typo in the name of ListBlock

xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/EmptyLinesBlock.java
=> [Java] Logic Related Reliability

xwiki-rendering-macros/xwiki-rendering-macro-footnotes/src/main/java/org/xwiki/rendering/internal/macro/footnote/PutFootnotesMacro.java
http://sonar.xwiki.org/issues/search#issues=21f1f5be-ef7a-4604-aa4e-10dd89071433
http://sonar.xwiki.org/issues/search#issues=67c68008-c948-4430-8d48-adde88d29582
=> [codestyle] isEmpty instead of size

xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/util/ListBuilder.java
hashcode method supplements the equals method
=> [codestyle] added hashcode method

xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/renderer/wikimodel/WikiModelGeneratorListener.java
http://sonar.xwiki.org/issues/search#issues=0976440d-8e99-4d3f-be02-bfbc83f0ab58
http://sonar.xwiki.org/issues/search#issues=62d75b47-9a61-453b-9deb-10059cbc864c
http://sonar.xwiki.org/issues/search#issues=e8bcf92c-9dbd-4986-9b16-983faab824de
=> [codestyle] readability

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/XHTMLChainingRenderer.java
Update XHTMLChainingRenderer.java by Changing the comparison to use the equals method.
=> [codestyle] Change the comparison to use the equals method

xwiki-rendering-macros/xwiki-rendering-macro-ctsreport/src/main/java/org/xwiki/rendering/internal/macro/ctsreport/Result.java
Reduce the number of returns of this method 4, down to the maximum allowed 3
=> [codestyle] Reduce the number of returns

xwiki-rendering-macros/xwiki-rendering-macro-ctsreport/src/main/java/org/xwiki/rendering/internal/macro/ctsreport/Test.java
Update Test.java by Reducing the number of returns of this method 4, down to 3.
=> [codestyle] Reduce the number of returns of this method 4, down to the maximum allowed 3

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java
Update XWikiSyntaxChainingRenderer.java by Adding a default case to the switch.
=> [codestyle] Add a default case to this switch

xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/DefaultXWikiGeneratorListener.java
Used isEmpty() to check whether the collection is empty or not.
=> [codestyle] change size>0 with isEmpty() function

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/parser/reference/GenericLinkReferenceParser.java
resolves the issue here http://sonar.xwiki.org/issues/search#issues=5b92bb8b-b188-465e-9831-c9899b38c111
=> [codestyle]  replaced indexof(string) with indexof(char) for speed

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/parser/reference/DefaultUntypedImageReferenceParser.java
Fixes issue found here: http://sonar.xwiki.org/issues/search#issues=093b55af-0b82-4fb4-a2f7-0b89d7cc0a0a
=> [codestyle] removed temporary variable

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/parser/reference/GenericLinkReferenceParser.java
Removed useless parentheses resolving issue here: http://sonar.xwiki.org/issues/search#issues=73daa6c7-9aa9-4607-8784-2690e1251f35
=> [codestyle] Removed useless parentheses

xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/renderer/wikimodel/WikiModelGeneratorListener.java
Resolved issues:-
1. http://sonar.xwiki.org/issues/search#issues=70c288ee-b86e-4ef2-9b83-69140f1563ce
2. http://sonar.xwiki.org/issues/search#issues=01ce0875-240b-4792-ba47-8da6bab7b399
=> [codestyle] Extract this increment or decrement operator into a dedicated statement

xwiki-rendering-syntaxes/xwiki-rendering-syntax-doxia/src/main/java/org/xwiki/rendering/internal/renderer/doxia/DoxiaListener.java
Resolves issue here http://sonar.xwiki.org/issues/search#issues=2cf92316-b86a-436f-b3ca-bc55ca813aec
=> [codestyle] Removed unused private method

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxEscapeWikiPrinter.java
resolves issue here http://sonar.xwiki.org/issues/search#issues=0183e8e7-085f-44f3-9d71-c9f4bfe15454
=> Changed to use isEmpty

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/reference/XWikiSyntaxResourceRenderer.java
Resolves issue here: http://sonar.xwiki.org/issues/search#issues=9153ccfb-c31c-491b-8280-4a4e1107481b
=> Removed unused parameter

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/transformation/DefaultTransformationManager.java
Resolves issue here: http://sonar.xwiki.org/issues/search#issues=a1a6ee90-dfc4-4295-9c4d-dac7ff79eb6f
=> Added missing javadoc tag

xwiki-rendering-syntaxes/xwiki-rendering-syntax-plain/src/main/java/org/xwiki/rendering/internal/parser/plain/PlainTextStreamParser.java
1. http://sonar.xwiki.org/issues/search#issues=a0fb63d2-a171-4637-baa7-e8029b9b0d22
2. http://sonar.xwiki.org/issues/search#issues=ca58e198-2ce7-4982-8d85-47eeca6dc665
=> [codestyle] Replace the synchronized class "StringBuffer" by an unsynchronized one such as "StringBuilder"

xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/WikiModelParserUtils.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiCommentHandler.java
http://sonar.xwiki.org/issues/search#issues=34d52c2c-46c6-4d5d-9bed-05c1ec5c9d94
http://sonar.xwiki.org/issues/search#issues=b78cb6e1-a64d-4cf2-9599-b35cc98f4986
http://sonar.xwiki.org/issues/search#issues=f15e4399-5199-44a3-afef-ef1ef17ba0b4
http://sonar.xwiki.org/issues/search#issues=90c32df4-9d2b-4fdc-81b5-d1bb04b1fa7f
http://sonar.xwiki.org/issues/search#issues=e05852e6-a136-467f-a8d7-c4ee1fe647d4
http://sonar.xwiki.org/issues/search#issues=2d18b070-e806-4218-9581-5533d3b2a318
=>  removed unused parameter from methods and calls to methods

xwiki-rendering-syntaxes/xwiki-rendering-syntax-plain/src/main/java/org/xwiki/rendering/internal/parser/plain/PlainTextStreamParser.java
http://sonar.xwiki.org/issues/search#issues=a0fb63d2-a171-4637-baa7-e8029b9b0d22
http://sonar.xwiki.org/issues/search#issues=ca58e198-2ce7-4982-8d85-47eeca6dc665
=> [codestyle] stringbuilder instead of stringbuffer

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/parser/reference/DefaultResourceReferenceParser.java
http://sonar.xwiki.org/issues/search#issues=befedb46-5df3-4bec-adc8-b1f60e6839ea
=> [codestyle] use char instead of length 1 string

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiSpanTagHandler.java
Resolves Issues:
http://sonar.xwiki.org/issues/search#issues=9999f5ad-20a9-4057-b5e6-26ea828d3a36
http://sonar.xwiki.org/issues/search#issues=75de3ffe-0877-4870-8057-953b7095380e
http://sonar.xwiki.org/issues/search#issues=c02316bd-f881-48e3-9ea9-692b5a34d62f
http://sonar.xwiki.org/issues/search#issues=c768ff71-7ec3-4d74-b191-6b2971ae14f1
=> Moved  string literals on the left side of string comparisons

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiHeaderTagHandler.java
Resolves: http://sonar.xwiki.org/issues/search#issues=9cfa909c-8ce8-4d4a-9479-39c377189407
=> Reordered the modifiers to comply with the Java Language Specification

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiHeaderTagHandler.java
Resolves issue here http://sonar.xwiki.org/issues/search#issues=4bb97ede-cd43-42dc-bd98-460444941739
=> Reordered modifiers to comply with the Java Language Specification

xwiki-rendering-syntaxes/xwiki-rendering-syntax-doxia/src/main/java/org/xwiki/rendering/internal/renderer/doxia/DoxiaPrinterAdapter.java
1.  http://sonar.xwiki.org/issues/search#issues=8fc93d95-c1d5-4cba-ad2c-9585f0f5d11e
2.  http://sonar.xwiki.org/issues/search#issues=ad207987-6fd4-4c10-bf8e-5b45504cdff1
=> [codestyle] Remove empty strings

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxEscapeWikiPrinter.java
1. http://sonar.xwiki.org/issues/search#issues=a434e23e-2cd5-4b77-b43b-2e96d6f7c186
2. http://sonar.xwiki.org/issues/search#issues=a61ea655-74ff-4a8e-b035-5e6532fe1777
3. http://sonar.xwiki.org/issues/search#issues=5eb04857-681d-4136-a521-bdff4bc820c6
4. http://sonar.xwiki.org/issues/search#issues=cbff6b56-b63b-4476-8c79-ff124d4fa4b8
5. http://sonar.xwiki.org/issues/search#issues=8fb93de5-42e2-4306-b66e-e178aa8323fa
=> [codestyle] Use isEmpty() instead if .size()

xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/macro/DefaultMacroContentParser.java
These are the issues I tried to solve:
http://sonar.xwiki.org/issues/search#issues=ce5bbaf7-450b-43a0-9068-9601fb04f4f4
http://sonar.xwiki.org/issues/search#issues=51a423d9-d670-40ee-b6bf-f4bf640ea6ca
=> Fix DefaultMacroContentParser issues

xwiki-rendering-macros/xwiki-rendering-macro-box/src/main/java/org/xwiki/rendering/macro/box/AbstractBoxMacro.java
These are the issues I tried to solve:
http://sonar.xwiki.org/issues/search#issues=aa32c990-3fd9-4031-a7d2-ea281087e3ca
=> Reduce Cyclomatic complexity

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiSpanTagHandler.java
Resolves issues: 
http://sonar.xwiki.org/issues/search#issues=31d9e905-ca6f-4dd6-8729-ae4545964c2b
http://sonar.xwiki.org/issues/search#issues=8994d753-e826-4f9c-886c-47990c067189
http://sonar.xwiki.org/issues/search#issues=9f496d6a-0a3b-45d9-bb97-54b2353517b4
http://sonar.xwiki.org/issues/search#issues=76876b1d-7dca-4b42-b271-511fadcffcce
=> Moved String literals to left side of comparison

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiXHTMLWhitespaceXMLFilter.java
Resolves issue here: http://sonar.xwiki.org/issues/search#issues=4063ed21-c258-4456-9712-630cb03d69aa
=> Merged collapsible if statement with enclosing one

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/renderer/ParametersPrinter.java
Resolves issue here: http://sonar.xwiki.org/issues/search#issues=f129db1e-719a-4767-bbd4-d7ec02fa4b0a
& here: http://sonar.xwiki.org/issues/search#issues=a003076a-d016-4c05-bea1-9b148f01bdca
=> Added missing @Deprecated annotation

xwiki-rendering-syntaxes/xwiki-rendering-syntax-doxia/src/main/java/org/xwiki/rendering/internal/renderer/doxia/DoxiaSinkListener.java
Resolves issue here: http://sonar.xwiki.org/issues/search#issues=16edcd12-da5e-41b7-a63d-45185d661a49
=> [codestyle] Removed empty strings

xwiki-rendering-api/src/main/java/org/xwiki/rendering/internal/renderer/reference/DefaultResourceReferenceTypeSerializer.java
Resolves issue here: http://sonar.xwiki.org/issues/search#issues=8c6a9eb3-cc62-424b-b280-ab09586c7f38
=> Changed StringBuffer to StringBuilder

xwiki-rendering-api/src/main/java/org/xwiki/rendering/block/PlainTextBlockFilter.java
These are the issues I tried to solve:
http://sonar.xwiki.org/issues/search#issues=e8de5232-8fe8-458c-8ab1-246933d4e1ff
http://sonar.xwiki.org/issues/search#issues=1b4243d4-9493-4180-bfe2-50606fd02910
=> Fix PlainTextBlockFilter issues

xwiki-rendering-test/src/main/java/org/xwiki/rendering/test/cts/IgnoredRenderingTestClassRunner.java
Issues:
http://sonar.xwiki.org/issues/search#issues=3da4d4bd-13ca-4369-b2ac-f1102174e685
http://sonar.xwiki.org/issues/search#issues=d512daec-e954-481f-b1ce-709e8ccc86d9
=> Prefer StringBuilder

xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/transformation/macro/MacroTransformation.java
Issues:
http://sonar.xwiki.org/issues/search#issues=53c212c6-3f76-45d5-9042-8b8dd59836b2
http://sonar.xwiki.org/issues/search#issues=da9c3696-2f49-4eeb-8f44-637c9fff0783
http://sonar.xwiki.org/issues/search#issues=a82e94e6-1211-465a-a862-2c5424c9118b http://sonar.xwiki.org/issues/search#issues=421d90bd-92f7-4df5-a8e8-8625a7c8428c
http://sonar.xwiki.org/issues/search#issues=50e19d5a-c3fa-42bc-93bf-808546e77b0b
=> Add getters and setters

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/reference/XWikiSyntaxResourceRenderer.java
Issues:
http://sonar.xwiki.org/issues/search#issues=5a54cdd5-3849-4734-918a-330d226029a2
http://sonar.xwiki.org/issues/search#issues=8bfb864e-ad79-4934-a8f3-3541ab2cbe3e
http://sonar.xwiki.org/issues/search#issues=6001a5de-4984-46d6-9039-bfc5b69902a8
=> Fix some XWikiSyntaxResourceRenderer issues

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/QueueListener.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/EventType.java
Issue: Consider using varargs for methods or constructors which take an array the last parameter. (x52)
One permalink: http://sonar.xwiki.org/issues/search#issues=a104439b-a2f0-4abe-87a5-bd132d3b2564
=> Update EventType.java - using varargs

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/QueueListener.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/chaining/EventType.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-doxia/src/main/java/org/xwiki/rendering/internal/renderer/doxia/DoxiaPrinterAdapter.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/macro/DefaultMacroManager.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/MacroId.java
Update DefaultMacroManager.java
Fixed http://sonar.xwiki.org/issues/search#issues=a6a2701c-f668-4392-9fa6-13dfdf251466
Update DoxiaPrinterAdapter.java
Fixed http://sonar.xwiki.org/issues/search#issues=6efc3f5c-99f8-4abb-bb3c-fabefba023c2
Update MacroId.java
Fixed http://sonar.xwiki.org/issues/search#issues=b79f65b8-dea8-47d6-ada6-7921845ae614
=> Fixed 3 coding violations

xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/DefaultXWikiGeneratorListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiCommentHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiReferenceTagHandler.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiXHTMLWhitespaceXMLFilter.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java
The links/description of each change is listed under the commit.
=> Fixed some coding violations

xwiki-rendering-transformations/xwiki-rendering-transformation-icon/src/main/java/org/xwiki/rendering/internal/transformation/icon/IconTransformation.java
issues:
http://sonar.xwiki.org/issues/search#issues=e3a8e98c-2559-4c9d-886d-313638dd5db5
=> Use isEmpty

xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/transformation/MacroTransformationContext.java
issues:
http://sonar.xwiki.org/issues/search#issues=062539bd-b5f9-4458-82cf-5a07dcda6636
http://sonar.xwiki.org/issues/search#issues=2083d6b7-44e0-480c-83d2-ff6b52b271e7
=> Rename isInline field

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/reference/ResourceReference.java
issues:
http://sonar.xwiki.org/issues/search#issues=671aca0e-14cd-48e9-9c5c-844b8be4fa1d
http://sonar.xwiki.org/issues/search#issues=b142fc96-5434-4a1b-b029-f53d545cf428
=> Rename isTyped field

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiWikiReference.java
issues:
http://sonar.xwiki.org/issues/search#issues=4775537a-d046-41fb-aef2-cda6c9aee916
http://sonar.xwiki.org/issues/search#issues=bced1665-79d3-4bc7-bbed-b5c13103555e
http://sonar.xwiki.org/issues/search#issues=fe335d96-58e1-4968-8fa9-5ecf197c3528
=> XWikiWikiReference issues

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/HeaderLevel.java
I have fixed issue:
http://sonar.xwiki.org/issues/search#issues=1ee8835e-6567-46f6-a9f1-ff591ad03cb1
=> Do not add empty string

xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/WikiModelParserUtils.java
Made PrefixIgnoredInlineFilterListener from existing anonymous class
=> [codestyle] Make anonymous class into named class

xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/renderer/wikimodel/WikiModelGeneratorListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/XHTMLChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/renderer/xhtml/link/AbstractXHTMLLinkTypeRenderer.java
Fixed issues:
http://sonar.xwiki.org/issues/search#issues=52d1618e-3a8d-4fbe-bc9b-30b27f4265a5
http://sonar.xwiki.org/issues/search#issues=475a0d63-f763-4e84-9972-e0ba5fe98684
http://sonar.xwiki.org/issues/search#issues=caad3e07-120a-4210-b4e6-6201071b3301
http://sonar.xwiki.org/issues/search#issues=d2bf5d63-c5c6-47fd-8b2b-866cc461bb0f
http://sonar.xwiki.org/issues/search#issues=dab07fab-ddfa-47af-990b-24b3a5177839
http://sonar.xwiki.org/issues/search#issues=ace57cab-e977-49cd-9457-f0dd4c7d6470
=> Code formatting and rename field

xwiki-rendering-api/src/main/java/org/xwiki/rendering/renderer/PrintRendererFactory.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/renderer/reference/ResourceReferenceSerializer.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/renderer/reference/ResourceReferenceTypeSerializer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/DefaultXWikiGeneratorListener.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/main/java/org/xwiki/rendering/internal/parser/xhtml/wikimodel/XWikiCommentHandler.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/transformation/macro/MacroTransformation.java
Fixed all of the issues with this rule: http://sonar.xwiki.org/coding_rules#rule_key=squid%3AS00103 and one column issue.
Didn't do [this one](http://sonar.xwiki.org/issues/search#issues=9e40abc8-4422-4590-9b23-6403d412b278) because it was a link, so would be best to keep on one line
=> [codestyle] Fixed all long line issues

xwiki-rendering-syntaxes/xwiki-rendering-syntax-event/src/main/java/org/xwiki/rendering/internal/renderer/event/EventsChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxMacroRenderer.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/WikiFormat.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/WikiParameters.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/WikiReference.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/impl/InternalWikiScannerContext.java, xwiki-rendering-wikimodel/src/main/java/org/xwiki/rendering/wikimodel/xwiki/xwiki20/XWikiSerializer2.java
Fixed all issues in `xwiki-rendering` for this rule: http://sonar.xwiki.org/coding_rules#rule_key=pmd%3AAppendCharacterWithChar
=> [codestyle] Avoid appending characters as strings in StringBuffer.append

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java
Resolves issues:
http://sonar.xwiki.org/issues/search#issues=6b75d251-a45a-4391-b726-58c47888f330
http://sonar.xwiki.org/issues/search#issues=9a20df47-672f-4fca-9a38-767978c7d7e6
=> [codestyle] Reduce Cyclomatic Complexity of method

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xwiki20/src/main/java/org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java
Reverts xwiki/xwiki-rendering#136
=> Revert "[codestyle] Reduce Cyclomatic Complexity of method"

xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/pom.xml, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/macro/macro1.test, xwiki-rendering-syntaxes/xwiki-rendering-syntax-xhtml/src/test/resources/xhtml10/specific/macro/macro2.test
* Fix the mutation threshold
* Add some test inside the module
=> XRENDERING-518: Macro content editable inline

xwiki-rendering-macros/xwiki-rendering-macro-box/src/main/java/org/xwiki/rendering/internal/macro/box/DefaultBoxMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/main/java/org/xwiki/rendering/macro/box/AbstractBoxMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/test/java/org/xwiki/rendering/macro/box/MandatoryContentBoxMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-box/src/test/resources/META-INF/components.txt, xwiki-rendering-macros/xwiki-rendering-macro-box/src/test/resources/macrobox8.test, xwiki-rendering-macros/xwiki-rendering-macro-box/src/test/resources/macrobox9.test, xwiki-rendering-macros/xwiki-rendering-macro-message/src/main/java/org/xwiki/rendering/internal/macro/message/AbstractMessageMacro.java
* Message macro now relies on AbstractBoxMacro
=> XRENDERING-536: Message macro should rely on AbstractBoxMacro

xwiki-rendering-macros/xwiki-rendering-macro-html/src/test/resources/macrohtml4.test, xwiki-rendering-macros/xwiki-rendering-macro-html/src/test/resources/macrohtml5.test, xwiki-rendering-macros/xwiki-rendering-macro-html/src/test/resources/macrohtml7.test
* Fix tests with the appropriate CDATA comments
=> XCOMMONS-1553: Remove XWikiDOMSerializer in favor of HtmlCleaner DomSerializer

xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/CompositeListener.java, xwiki-rendering-api/src/main/java/org/xwiki/rendering/listener/QueueListener.java
Jira issue: https://jira.xwiki.org/browse/XRENDERING-632
=> XRENDERING-632: Figure and figure caption events are not handled by the composite and queue listener

xwiki-rendering-test/src/main/java/org/xwiki/rendering/test/cts/TestDataParser.java
Jira issue: https://jira.xwiki.org/browse/XRENDERING-639
=> XRENDERING-639: Allow recursive inheritance for the CTS

xwiki-rendering-transformations/xwiki-rendering-transformation-macro/pom.xml, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/macro/DefaultMacroCategoryManager.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/transformation/macro/DefaultMacroTransformationConfiguration.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/AbstractMacro.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/MacroCategoryManager.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/transformation/macro/MacroTransformationConfiguration.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/DefaultMacroTransformationConfigurationTest.java
Jira: https://jira.xwiki.org/browse/XRENDERING-676
=> XRENDERING-676: Introduce the notion of hidden macro categories

xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/DefaultFigureTypeRecognizer.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/java/org/xwiki/rendering/macro/figure/DefaultFigureTypeRecognizerTest.java
Jira: https://jira.xwiki.org/browse/XRENDERING-680
=> XRENDERING-680: Figure type recognition is sensible to empty lines

xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/FigureMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/internal/macro/figure/FigureTypeRecognizerMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/macro/figure/FigureMacroParameters.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/java/org/xwiki/rendering/macro/figure/FigureType.java, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/resources/ApplicationResources.properties, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/test/resources/macrofigure7.test
Jira: https://jira.xwiki.org/browse/XRENDERING-681
=> XRENDERING-681: Add ability to force a figure type (figure or table)

xwiki-rendering-api/src/main/java/org/xwiki/rendering/parser/ParseException.java, xwiki-rendering-syntaxes/xwiki-rendering-syntax-wikimodel/src/main/java/org/xwiki/rendering/internal/parser/wikimodel/AbstractWikiModelParser.java
Jira: https://jira.xwiki.org/browse/XRENDERING-683
=> XRENDERING-683: Return a parse exception in case of stackoverflow when parsing with javacc

xwiki-rendering-macros/xwiki-rendering-macro-html/src/test/resources/macrohtml17.test, xwiki-rendering-macros/xwiki-rendering-macro-html/src/test/resources/macrohtml18.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/TocTreeBuilder.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc1.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc10.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc11.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc13.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc2.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc3.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc4.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc7.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc8.test, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/wikimodel/macrotoc9.test, xwiki-rendering-standalone/src/test/java/org/xwiki/rendering/example/ExampleTest.java
- Add CSS class to the tree generated by the TocTreeBuilder
=> XRENDERING-690: Update TOC macro DOM root element to make it easier to style and to navigate

xwiki-rendering-api/src/main/resources/ApplicationResources_ja.properties, xwiki-rendering-api/src/main/resources/ApplicationResources_mr.properties, xwiki-rendering-macros/xwiki-rendering-macro-content/src/main/resources/ApplicationResources_ja.properties, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/resources/ApplicationResources.properties, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/resources/ApplicationResources_de.properties, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/resources/ApplicationResources_fr.properties, xwiki-rendering-macros/xwiki-rendering-macro-figure/src/main/resources/ApplicationResources_ja.properties, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/resources/ApplicationResources_ja.properties, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/resources/ApplicationResources_mr.properties
Co-authored-by: Suguru Hirahara <suguru@pm.me>
=> [Misc] Updated translations.

pom.xml, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/macro/toc/TocMacroParameters.java
Jira: https://jira.xwiki.org/browse/XRENDERING-719
=> XRENDERING-719: Make the numbered property advanced

xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/AbstractTocMacro.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/AbstractTocTreeBuilderFactory.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/DefaultTocEntriesResolver.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/DefaultTocTreeBuilderFactory.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/TocTreeBuilder.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/macro/toc/TocEntriesResolver.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/macro/toc/TocEntryDecorator.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/macro/toc/TocEntryExtension.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/macro/toc/TocTreeBuilderFactory.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/resources/META-INF/components.txt, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/java/org/xwiki/rendering/internal/macro/toc/DefaultTocEntriesResolverTest.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/java/org/xwiki/rendering/internal/macro/toc/DefaultTocTreeBuilderFactoryTest.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/java/org/xwiki/rendering/macro/toc/NoWikiModelIntegrationTests.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/java/org/xwiki/rendering/macro/toc/ToCExtensionsIntegrationTests.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/java/org/xwiki/rendering/macro/toc/TocMacroTest.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/java/org/xwiki/rendering/macro/toc/WikiModelIntegrationTests.java, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/test/resources/tocextensions/macrotoc1.test
Jira: https://jira.xwiki.org/browse/XRENDERING-704
Note a PR will be created for xwiki-platform-export-pdf-api on xwiki-platform
**TODO**
=> XRENDERING-704: Provide a mechanism to customize the toc entries modularily

xwiki-rendering-macros/xwiki-rendering-macro-toc/pom.xml, xwiki-rendering-macros/xwiki-rendering-macro-toc/src/main/java/org/xwiki/rendering/macro/toc/TocMacroParameters.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/parameter/ParameterValueTooHighException.java, xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/parameter/ParameterValueTooLowException.java
The rendering side of what is already described in https://github.com/xwiki/xwiki-commons/pull/1075.
* Prefers squash: Yes
=> Move to Jakarta based application servers
